version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flux_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flux
      POSTGRES_USER: flux_user
      POSTGRES_PASSWORD: flux_password
    ports:
      - "5432:5432"
    volumes:
      - flux_pgdata:/var/lib/postgresql/data

volumes:
  flux_pgdata:
