ALTER TABLE users 
ADD COLUMN rule1_name VARCHAR(50) DEFAULT 'Necessidades' NOT NULL,
ADD COLUMN rule1_percent INT DEFAULT 50 NOT NULL,
ADD COLUMN rule2_name VARCHAR(50) DEFAULT 'Desejos' NOT NULL,
ADD COLUMN rule2_percent INT DEFAULT 30 NOT NULL,
ADD COLUMN rule3_name VARCHAR(50) DEFAULT 'Poupança/Dívidas' NOT NULL,
ADD COLUMN rule3_percent INT DEFAULT 20 NOT NULL;
